name: Project Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Python Setup
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.1" # Updated Python version

      # Node Setup
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "16"

      # ML Checks
      - name: ML - Install dependencies
        run: |
          cd ML
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: ML - Run tests
        run: |
          cd ML
          pytest tests/

      # Backend Checks
      - name: Backend - Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Backend - Run tests
        run: |
          cd backend
          pytest tests/

      # Frontend Checks
      - name: Frontend - Install dependencies
        run: |
          cd frontend
          npm install --force

      - name: Frontend - Run tests
        run: |
          cd frontend
          CI=true npm test --passWithNoTests
